spring:
  jpa:
    hibernate:
      ddl-auto: update
spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

server:
  port: 8082
spring:
  application:
    name: car-service






