server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: motorbike-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.hostname}:${spring.application.instance_id:${random.value}}







